### ISSUE TITLE
AnimatedRegion could not obtain AnimatedWithChildren base class  

### ISSUE THREAD

**Issue by dinukasal** [airbnb/react-native-maps#1303]
I get the error "AnimatedRegion could not obtain AnimatedWithChildren base class " when app is loading the bundle from npm,

My package.json dependencies,

"dependencies": {
    "mobx": "^3.1.9",
    "mobx-react": "^4.1.8",
    "react": "15.4.1",
    "react-native": "0.42.3",
    "react-native-maps": "^0.13.0",
    "react-native-router-flux": "^3.38.1",
    "react-native-vector-icons": "^4.0.1",
    "socket.io-client": "^1.7.3"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "15.4.1"
  },

But in the new react and react-native version react-native-maps@0.13.0 works well, not with these combination. What could be a possible solution?

This is the error,

![6ru0x](https://cloud.githubusercontent.com/assets/9583917/25749570/a1c22184-31cc-11e7-8fff-f5b3fe92c8e4.jpg)

**Comment by dinukasal** [comment]
Solved with using yarn.. I was using npm and go the error.

**Comment by adhambadr** [comment]
@dinukasal could you explain how exacty ? Im running at the same error, rn 0.44, react 16.0.0.alpha, and tried yarn on the root package it resolved dependancies but then prop-type is missing yarn add prop-types then this error.

**Comment by alexpriceco** [comment]
I also am running into this, not sure what the fix is based on your May 12 comment, @dinukasal. I removed my node_modules folder, and ran `yarn`, but am still getting this error.

**Comment by alainib** [comment]
got the same problem only when i enable "JS minify" in "dev settings" when i shake the smartphone.
un check it solve the error showing

**Comment by aMarCruz** [comment]
I think Yarn is not adding typings, it is VS Code. But anyway, I have this issue because I'm debuging with the "JS Minify" option checked on the Dev Menu.

The comparisson at the top of react-native-maps/lib/compnents/AnimatedRegion.js is wrong in minified buils in debug mode:
![image](https://user-images.githubusercontent.com/6636980/37185270-2e45c5c8-2305-11e8-8366-a196c765bcff.png)

...because the name "AnimatedWithChildren" is shorten. Tracing the output I can see the right `AnimatedWithChildren` object is there:
![image](https://user-images.githubusercontent.com/6636980/37185344-7a04dc1a-2305-11e8-9ddd-d044bf6de0c6.png)

but its name is not "AnimatedWithChildren" anymore, so the error is generated.

BTW: not all of `propTypes` are availables in production builds.

**Comment by 0x77dev** [comment]
guys:
```
AnimatedRegion could not obtain AnimatedWithChildren base class
- node_modules/expo/build/logs/LogSerialization.js:148:4 in w
- node_modules/expo/build/logs/LogSerialization.js:41:24 in <unknown>
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in p
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:30 in <unknown>
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in p
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:135:28 in n
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:170:17 in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in c
- node_modules/promise/setimmediate/core.js:200:23 in b
- node_modules/promise/setimmediate/core.js:66:12 in _
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:169:27 in u
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:192:12 in <unknown>
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:216:13 in <unknown>
- node_modules/expo/build/logs/LogSerialization.js:7:0 in serializeLogDataAsync
- node_modules/expo/build/logs/RemoteLogging.js:28:79 in <unknown>
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in p
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:30 in <unknown>
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in p
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:135:28 in n
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:170:17 in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in c
- node_modules/promise/setimmediate/core.js:200:23 in b
- node_modules/promise/setimmediate/core.js:66:12 in _
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:169:27 in u
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:192:12 in <unknown>
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:216:13 in <unknown>
- node_modules/expo/build/logs/RemoteLogging.js:13:0 in enqueueRemoteLogAsync
- node_modules/expo/build/logs/RemoteConsole.js:92:44 in p
- node_modules/expo/build/logs/RemoteConsole.js:82:30 in <unknown>
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in <unknown>
- node_modules/react-native-maps/lib/components/AnimatedRegion.js:6:74 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in g
- node_modules/react-native-maps/lib/components/MapView.js:23:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in g
- node_modules/react-native-maps/index.js:1:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in g
* src/homescreen.js:10:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in g
* App.js:17:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in g
- node_modules/expo/AppEntry.js:4:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in g
- node_modules/metro/src/lib/polyfills/require.js:197:45 in f
* null:null in global code

```

**Comment by adilusman51** [comment]
Hi, for me this appeared when I ran expo with minify `expo start -c --minify`

```
AnimatedRegion could not obtain AnimatedWithChildren base class
at node_modules/expo/build/logs/LogSerialization.js:155:18 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
at node_modules/expo/build/logs/LogSerialization.js:7:0 in serializeLogDataAsync
at node_modules/expo/build/logs/RemoteLogging.js:29:59 in enqueueRemoteLogAsync
at node_modules/expo/build/logs/RemoteLogging.js:14:0 in enqueueRemoteLogAsync
at node_modules/react-native-maps/lib/components/AnimatedRegion.js:6:12 in <global>
at node_modules/react-native-maps/lib/components/MapView.js:26:0 in <global>
at node_modules/react-native-maps/index.js:1:0 in <global>
at src/paper/StaticMapView.tsx:2:0 in <global>
at src/paper/index.ts:36:0 in <global>
at src/navigation/AddBookingTabs.tsx:1:0 in <global>
at src/navigation/index.ts:1:0 in <global>
at App.tsx:4:0 in <global>
at node_modules/expo/AppEntry.js:3:0 in <global>
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=true:3063:3 in global code
```
Platform iOS, development true, minify true

Any ideas how to resolve this?

**Comment by jpamarohorta** [comment]
Hello, we are still experiencing this issue in both `expo start --minify` and EAS preview builds. Any ideas how to solve this issue or disable minification for the EAS preview build process? Thank you!
