### ISSUE TITLE
[iOS] InitialRegion doesn't work correctly in Apple Maps

### ISSUE THREAD

**Issue by KarlosQ** [airbnb/react-native-maps#1577]
In my project  InitialRegion doesn't work correctly now that I've updated from RN 0.42.3 and react native maps 0.13.0 to RN 0.47.1 and react native mapas 0.16.2.

The issue is that although I write the initial region the map is show me the world when my longitudeDelta y latitudeDelta is correct. For solve this problem I must to do:

```
onMapReady={() => this.map.animateToRegion({
       latitude: this.props.latitude,
       longitude: this.props.longitude,
       longitudeDelta: LONGITUDE_DELTA ,
       latitudeDelta: LATITUDE_DELTA
}, 1)}
```

But in RN 0.42.3, 0.13.0 and in the new version but with Android and Google Maps the maps works perfect with InitialRegion.

**Comment by petha** [comment]
I've checked the code and it seems like the fix for #1563 broke IOS. 

The IOS code uses nativeProp region but after the commit the frontend component (lib/components/MapView.js) sets initialRegion

`this.map.setNativeProps({ initialRegion });`

instead of 

```
const region = this.props.region || this.props.initialRegion;
this.map.setNativeProps({ region });
```

So that the IOS code won't set the initial region.

**Comment by omaksi** [comment]
I'm having a similar issue with Google Maps on iOS wit latest RN and maps. 
`initialRegion` is only set correctly on first render.

**Comment by jatsrt** [comment]
I need to confirm, but this same change seems to be effecting scrolling of the map.  If you have initialRegion or region set on MapView on iOS, when you scroll the map, it will pop back to the initial region.

**Comment by RobTS** [comment]
Experiencing this as well. iOS, Google Maps, since upgrading from 0.15.3.

InitialRegion will be set correctly the first time, but after minimizing and reopening the app it sits in 0,0 with a screen full of seawater.

**Comment by heysailor** [comment]
+1, also on android.

**Comment by Metroninja** [comment]
So I fixed this on iOS by updating `MapView.js` ComponentDidMount to:
```
  componentDidMount() {
    const { isReady } = this.state;
    if (isReady) {
      this._updateStyle();
    }
    if (Platform.OS === 'ios' && this.props.initialRegion) {
      this.map.setNativeProps({ region: this.props.initialRegion });
    } else if(Platform.OS === 'ios') {
      this.map.setNativeProps({ region: this.props.region });
    }
  }
```

This covers both cases for ios where if you either set initialRegion, or region (I only set a region personally).  It is theft and slight modification from a fix [will link in an edit] I used back when 16.0 was out to get this working again.  Not sure why settingNativeProps works in ComponentDidMount versus onMapReady but this fixes it so...

**Comment by kesha-antonov** [comment]
+1
```_onMapReady``` is fired on ```onRegionChangeComplete```

First time ```onRegionChangeComplete``` fired with correct values.
Second time - with initialRegion.

Anybody solved this?

Tried fork of @petha and code of @Metroninja  . Does not solve for me

**Comment by kesha-antonov** [comment]
Can confirm that:
ios 1.15.3 works fine. ```onRegionChangeComplete``` called once
ios 1.16.2 has bug. ```onRegionChangeComplete``` called twice
android 1.16.2 works fine

**Comment by kesha-antonov** [comment]
Hey guys, check my PR https://github.com/airbnb/react-native-maps/pull/1597
It fixes for me

What do you think? Is it proper fix?

**Comment by omaksi** [comment]
Just FYI, my current workaround is doing `animateToRegion` in the screen's `componentDidMount`

Seems working so far

```
componentDidMount() {
  this.map.animateToRegion(initialRegion, 1)
}
```

**Comment by nenti** [comment]
For my @omaksi didn't work as workaround. Adding requestAnimactionFrame helped though.

```
componentDidMount() {
    requestAnimationFrame(() => {
      this.mapRef.animateToRegion(this.initialRegion, 1)
    })
  }
```

**Comment by jordanmkoncz** [comment]
@omaksi @nenti thanks for posting your solution, I was able to use it to create a workaround for an issue with `react-native-maps` not rendering correctly the second time when using `initialRegion` (see above referenced comments).
