### ISSUE TITLE
Execution failed for task ':react-native-maps:mergeReleaseResources'. - Error: File path too long on Windows, keep below 240 characters

### ISSUE THREAD

**Issue by sathvikp** [airbnb/react-native-maps#588]
On the [example in the repo](https://github.com/airbnb/react-native-maps/tree/v0.8.2/example), when running ` react-native run-android` on Windows (10 x64), it fails with:
```
Execution failed for task ':react-native-maps:mergeReleaseResources'.
> C:\Users\admin\Desktop\Sathvik\react-native-maps\example\node_modules\react-na  tive-maps\android\build\intermediates\exploded-aar\com.google.android.gms\play-s  ervices-base\9.4.0\res\drawable-mdpi-v4\common_google_signin_btn_text_light_disa  bled.9.png: Error: File path too long on Windows, keep below 240 characters : C:  \Users\admin\Desktop\Sathvik\react-native-maps\example\node_modules\react-native  -maps\android\build\intermediates\exploded-aar\com.google.android.gms\play-servi  ces-base\9.4.0\res\drawable-mdpi-v4\common_google_signin_btn_text_light_disabled  .9.png
```

+ react-native-maps version: 0.8.2
+ react-native version: 0.32.1
+ npm version: 3.9.6
+ node version: v6.2.1

Full log:
```
admin@local MINGW64 ~/Desktop/Sathvik/react-native-maps/example ((v0.8.2))
$ react-native run-android
JS server already running.
Running C:\Users\admin\android-sdks/platform-tools/adb reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && gradlew.bat installDe bug...
Support for running Gradle using Java 6 has been deprecated and will be removed in  Gradle 3.0
Observed package id 'add-ons;addon-google_apis-google-23' in inconsistent location  'C:\Users\admin\android-sdks\add-ons\addon-google_apis-google-23-1' (Expected 'C: \Users\admin\android-sdks\add-ons\addon-google_apis-google-23')
Already observed package id 'add-ons;addon-google_apis-google-23' in 'C:\Users\adm in\android-sdks\add-ons\addon-google_apis-google-23'. Skipping duplicate at 'C:\Us ers\admin\android-sdks\add-ons\addon-google_apis-google-23-1'
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
Incremental java compilation is an incubating feature.
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
Default language level for compileSdkVersion 'android-23' is 1.7, but the JDK used  is 1.6, so the JDK language level will be used.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-maps:preBuild UP-TO-DATE
:react-native-maps:preReleaseBuild UP-TO-DATE
:react-native-maps:compileReleaseNdk UP-TO-DATE
:react-native-maps:compileLint
:react-native-maps:copyReleaseLint UP-TO-DATE
:react-native-maps:checkReleaseManifest
:react-native-maps:preDebugAndroidTestBuild UP-TO-DATE
:react-native-maps:preDebugBuild UP-TO-DATE
:react-native-maps:preDebugUnitTestBuild UP-TO-DATE
:react-native-maps:preReleaseUnitTestBuild UP-TO-DATE
:react-native-maps:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-maps:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-maps:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-maps:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-D ATE
:react-native-maps:prepareComFacebookReactReactNative0321Library UP-TO-DATE
:react-native-maps:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBase940Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesBasement940Library UP-TO- DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesMaps940Library UP-TO-DATE
:react-native-maps:prepareComGoogleAndroidGmsPlayServicesTasks940Library UP-TO-DAT E
:react-native-maps:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-maps:prepareReleaseDependencies
:react-native-maps:compileReleaseAidl UP-TO-DATE
:react-native-maps:compileReleaseRenderscript UP-TO-DATE
:react-native-maps:generateReleaseBuildConfig UP-TO-DATE
:react-native-maps:mergeReleaseShaders UP-TO-DATE
:react-native-maps:compileReleaseShaders UP-TO-DATE
:react-native-maps:generateReleaseAssets UP-TO-DATE
:react-native-maps:mergeReleaseAssets UP-TO-DATE
:react-native-maps:generateReleaseResValues UP-TO-DATE
:react-native-maps:generateReleaseResources UP-TO-DATE
:react-native-maps:mergeReleaseResources
C:\Users\admin\Desktop\Sathvik\react-native-maps\example\node_modules\react-native -maps\android\build\intermediates\exploded-aar\com.google.android.gms\play-service s-base\9.4.0\res\drawable-mdpi-v4\common_google_signin_btn_text_light_disabled.9.p ng: Error: File path too long on Windows, keep below 240 characters : C:\Users\adm in\Desktop\Sathvik\react-native-maps\example\node_modules\react-native-maps\androi d\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.4.0 \res\drawable-mdpi-v4\common_google_signin_btn_text_light_disabled.9.png
:react-native-maps:mergeReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:mergeReleaseResources'.
> C:\Users\admin\Desktop\Sathvik\react-native-maps\example\node_modules\react-nati ve-maps\android\build\intermediates\exploded-aar\com.google.android.gms\play-servi ces-base\9.4.0\res\drawable-mdpi-v4\common_google_signin_btn_text_light_disabled.9 .png: Error: File path too long on Windows, keep below 240 characters : C:\Users\a dmin\Desktop\Sathvik\react-native-maps\example\node_modules\react-native-maps\andr oid\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.4 .0\res\drawable-mdpi-v4\common_google_signin_btn_text_light_disabled.9.png

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug op tion to get more log output.

BUILD FAILED

Total time: 18.582 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by CoreyAR** [comment]
I was able to solve this by updating Google Repository in the Android SDK Manager.

**Comment by sathvikp** [comment]
I have the latest Google Repository - version 32 (Installed Android Studio
afresh just yesterday).
I tried deleting and reinstalling it - still the same ...
Did you do anything in addition to that?

**Comment by CoreyAR** [comment]
After I updated Google Repository, I got another error that I resolved with `./gradlew clean`.

**Comment by sathvikp** [comment]
Ran `gradlew clean` and upgraded Java, npm and all installed packages - didn't fix it

Also reported on [facebook/react-native#9980](https://github.com/facebook/react-native/issues/9980)

**Comment by ariefadvani** [comment]
hy, i have a problem error while running apps with react native
this is error : 
:react-native-maps:prepareReleaseDependencies
:react-native-maps:compileReleaseAidl
:react-native-maps:compileReleaseNdk UP-TO-DATE
:react-native-maps:compileLint
:react-native-maps:copyReleaseLint UP-TO-DATE
:react-native-maps:compileReleaseRenderscript
:react-native-maps:generateReleaseBuildConfig
:react-native-maps:generateReleaseResValues
:react-native-maps:generateReleaseResources
:react-native-maps:mergeReleaseResources
:react-native-maps:processReleaseManifest
:react-native-maps:processReleaseResources
C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\re
s\drawable\common_google_signin_btn_icon_dark.xml:9:27-79: AAPT: No resource found that matches the given name (at 'drawable'
with value '@drawable/common_google_signin_btn_icon_dark_focused').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\re
s\drawable\common_google_signin_btn_icon_dark.xml:11:27-78: AAPT: No resource found that matches the given name (at 'drawable'
 with value '@drawable/common_google_signin_btn_icon_dark_normal').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\re
s\drawable\common_google_signin_btn_icon_light.xml:9:27-80: AAPT: No resource found that matches the given name (at 'drawable'
 with value '@drawable/common_google_signin_btn_icon_light_focused').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\re
s\drawable\common_google_signin_btn_icon_light.xml:11:27-79: AAPT: No resource found that matches the given name (at 'drawable
' with value '@drawable/common_google_signin_btn_icon_light_normal').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\re
s\drawable\common_google_signin_btn_text_dark.xml:11:27-79: AAPT: No resource found that matches the given name (at 'drawable'
 with value '@drawable/common_google_signin_btn_text_dark_focused').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\re
s\drawable\common_google_signin_btn_text_dark.xml:13:27-78: AAPT: No resource found that matches the given name (at 'drawable'
 with value '@drawable/common_google_signin_btn_text_dark_normal').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\re
s\drawable\common_google_signin_btn_text_light.xml:9:27-80: AAPT: No resource found that matches the given name (at 'drawable'
 with value '@drawable/common_google_signin_btn_text_light_focused').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.2.4\re
s\drawable\common_google_signin_btn_text_light.xml:11:27-79: AAPT: No resource found that matches the given name (at 'drawable
' with value '@drawable/common_google_signin_btn_text_light_normal').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\res\merged\release\drawable\common_google_signin_btn_icon_dark.x
ml:7: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_bt
n_icon_dark_focused').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\res\merged\release\drawable\common_google_signin_btn_icon_dark.x
ml:10: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_b
tn_icon_dark_normal').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\res\merged\release\drawable\common_google_signin_btn_icon_light.
xml:7: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_b
tn_icon_light_focused').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\res\merged\release\drawable\common_google_signin_btn_icon_light.
xml:10: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_
btn_icon_light_normal').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\res\merged\release\drawable\common_google_signin_btn_text_dark.x
ml:9: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_bt
n_text_dark_focused').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\res\merged\release\drawable\common_google_signin_btn_text_dark.x
ml:12: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_b
tn_text_dark_normal').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\res\merged\release\drawable\common_google_signin_btn_text_light.
xml:7: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_b
tn_text_light_focused').

C:\Users\Arief Advani\Desktop\Belajar React Native\pushnotifikasi\farid safi chatapp\react-native-gifted-chat-master\example\n
ode_modules\react-native-maps\lib\android\build\intermediates\res\merged\release\drawable\common_google_signin_btn_text_light.
xml:10: error: Error: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_
btn_text_light_normal').


:react-native-maps:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-maps:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Please help me ...

**Comment by JamesBorn0429** [comment]
There are some issues to build my project.
I ask for your help. Please help me.
Thanks!

> Task :react-native-youtube:generateDebugBuildConfig FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
167 actionable tasks: 167 executed
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\@react-native-community\viewpager\android\src\main\java\com\reactnativecommunity\viewpager\ReactViewPagerManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-camera\android\src\main\java\com\google\android\cameraview\Camera2.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-device-info\android\src\main\java\com\learnium\RNDeviceInfo\RNDeviceModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-fs\android\src\main\java\com\rnfs\RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-localize\android\src\main\java\com\reactcommunity\rnlocalize\RNLocalizeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-onesignal\android\src\main\java\com\geektime\rnonesignalandroid\RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-video\android\src\main\java\com\android\vending\expansion\zipfile\APEZProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-video\android\src\main\java\com\brentvatne\react\ReactVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-youtube:generateDebugBuildConfig'.
> java.nio.file.AccessDeniedException: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-youtube\android\build\generated\source\buildConfig\debug

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 53s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\@react-native-community\viewpager\android\src\main\java\com\reactnativecommunity\viewpager\ReactViewPagerManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-camera\android\src\main\java\com\google\android\cameraview\Camera2.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-device-info\android\src\main\java\com\learnium\RNDeviceInfo\RNDeviceModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-fs\android\src\main\java\com\rnfs\RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-localize\android\src\main\java\com\reactcommunity\rnlocalize\RNLocalizeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-onesignal\android\src\main\java\com\geektime\rnonesignalandroid\RNOneSignal.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-video\android\src\main\java\com\android\vending\expansion\zipfile\APEZProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-video\android\src\main\java\com\brentvatne\react\ReactVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-youtube:generateDebugBuildConfig'.
> java.nio.file.AccessDeniedException: D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\react-native-youtube\android\build\generated\source\buildConfig\debug

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 53s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at then.result (D:\JamesBorn0429\React Native\Talentora-RN-master\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
