### ISSUE TITLE
Multi-instance Memory Leak

### ISSUE THREAD

**Issue by gregberns** [airbnb/react-native-maps#939]
On Android, when using react-native-maps with the react-native-router-flux router, when a map is loaded over and over, there is a large memory leak that can result in an application crash.

It appears that the map instance is not disposed of. After a short look at a heap dump, it seems like 'AirMapView' is not getting disposed. I suspect this is a native Java wrapper around the Google Maps instance.

It looks like the issue was introduced after `0.10.1`, and exists in `0.11.0`.

I've created a simple project to make this issue easy to reproduce.

https://github.com/gregberns/ReactNativeMapTest

I haven't done much work with this project or RN's native components, but I'll try and dig in a little further and see where it can go, but any help to resolve this would be very welcome.

**Comment by gregberns** [comment]
Looks this was introduced by PR #694, made by @felipecsl , merged by @spikebrehm. Calls to `AirMapView.doDestroy()` were removed to fix #414. Thats the only change I can see that seems like it could cause the extra map instances.

**Comment by felipecsl** [comment]
Thanks for reporting this. Sounds like a legit issue. We'll take a look!

**Comment by proProbe** [comment]
how is it going with this bug? Im currently running into this problem!

**Comment by felipecsl** [comment]
no progress yet!

**Comment by gregberns** [comment]
Anything we can do to help? Is it a pretty deep issue? Any details you can share with the underlying issue? Thx

**Comment by aashna208** [comment]
On debugging I found two causes for this memory leak:
1. The google maps api holds the instance to the context if the location is enabled. Here is the tracking issue: https://code.google.com/p/gmaps-api-issues/issues/detail?id=9233#makechanges. This seems to be happening even in version 9.8.0 
2. AirMapManager is leaking because we are keeping the ThemedReactContext reference. I have a fix for this one.

**Comment by mattshen** [comment]
@aashna208 can you post the fix here. I would like to give it a try.

**Comment by mattshen** [comment]
Just created a PR (https://github.com/airbnb/react-native-maps/pull/1130). It reverts some changes in PR#694, and puts some extra patch (https://github.com/IjzerenHein/react-native-maps/commit/14ca6f73078a2e8dedccfeefe8a037d55f03c59c).

**Comment by psam44** [comment]
@mattshen I had a look at your PR. Without knowing it, in my issue 1102 I came to a similar conclusion, with a fix fully in AirMapView.java (no change in AirMapManager.java). (I don't know if one is better than the other).

**Comment by mattshen** [comment]
Hi @psam44, Just saw you've updated issue#1102 with more details. Will try that out later

**Comment by lelandrichardson** [comment]
Closed - should be fixed by #1130 thanks @mattshen!

**Comment by IjzerenHein** [comment]
Has anyone tested this yet? I still seem to be loosing memory when showing and hiding MapView.
Will try to investigate.

**Comment by freeljt** [comment]
With react-native-maps: "0.14.0", I still see memory jumping by ~100Mb when rendering <MapView /> by looking at perf monitor in iOS simulator. And the memory usage did not fully recover after the map component unmount. 
Is there anyway to reduce the ram usage or recover from the previous rendering?

**Comment by mattshen** [comment]
same on Android, the memory isn't fully recovered after unmounting the map view. I guess it's somehow related to GC. However, we haven't experienced any crashes or serious issues regarding this.

**Comment by austin43** [comment]
Experiencing the same problem on iOS simulator @freejlt

Before mounting ~10 different maps within the span of a minute:
https://www.dropbox.com/s/qc3lo8e6s796maf/Screenshot%202017-06-06%2016.05.11.png?dl=0

After:
https://www.dropbox.com/s/vavli8gcaxkka6d/Screenshot%202017-06-06%2016.06.06.png?dl=0

It drops back down after a while from what I assume is RN's GC, but not sure of an interim fix.

**Comment by MadhukarSP** [comment]
With "react-native-maps": "^0.15.2", (only on Android)  I am still facing memory leak issue. The memory is not fully recovered after the map component unmount. I guess when component unmounts, Map View instance is not considered as a candidate for garbage collection.  

Also in "AirMapView.java" file, the following method is not doing anything. 

@Override
public void onHostDestroy() { }

Please shed some lights on how to address this issue. Else please fix the issue as part of next react-native-maps version release. [As part of our (react-native) application, we are using maps is two scenes. User switches between these scenes often, hence the issue is more prominent to occur].

**Comment by jeffreymendez1993** [comment]
memory issues here.
